# Generated by Django 3.2.7 on 2021-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='longitude',
        ),
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.CharField(default='0deg', max_length=100),
        ),
        migrations.AddField(
            model_name='marker',
            name='lng',
            field=models.CharField(default='0deg', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
